owner: Rentr-UK
repo: Rentmigo-uptime

sites:
  # Production
  - name: "[Prod] Website"
    url: https://rentmigo.co.uk
    expectedStatusCodes:
      - 200
      - 301
      - 429
  - name: "[Prod] Login"
    url: https://rentmigo.co.uk/login
    expectedStatusCodes:
      - 200
      - 301
      - 429
  - name: "[Prod] Auth API"
    url: https://rentmigo.co.uk/api/auth
    expectedStatusCodes:
      - 200
      - 301
      - 401
      - 429
  - name: "[Prod] Landlord API"
    url: https://rentmigo.co.uk/api/v1/landlord
    expectedStatusCodes:
      - 200
      - 301
      - 401
      - 429
  - name: "[Prod] Health Check"
    url: https://rentmigo.co.uk/api/health
    expectedStatusCodes:
      - 200
      - 301
      - 429

  # Staging
  - name: "[Staging] Website"
    url: https://staging.rentmigo.co.uk
    expectedStatusCodes:
      - 200
      - 301
      - 401
  - name: "[Staging] Login"
    url: https://staging.rentmigo.co.uk/login
    expectedStatusCodes:
      - 200
      - 301
      - 401
  - name: "[Staging] Auth API"
    url: https://staging.rentmigo.co.uk/api/auth
    expectedStatusCodes:
      - 200
      - 301
      - 401
  - name: "[Staging] Landlord API"
    url: https://staging.rentmigo.co.uk/api/v1/landlord
    expectedStatusCodes:
      - 200
      - 301
      - 401
  - name: "[Staging] Health Check"
    url: https://staging.rentmigo.co.uk/api/health
    expectedStatusCodes:
      - 200
      - 301
      - 401

status-website:
  baseUrl: /Rentmigo-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rentr UK Status
  theme: light
  introTitle: "**Rentr UK** uptime monitor and status page."
  introMessage: Real-time uptime data for Rentr UK services. Target uptime 99.5%.
