owner: Rentr-UK
repo: Rentmigo-uptime

sites:
  # Production
  - name: "[Prod] Website"
    url: https://rentmigo.co.uk
  - name: "[Prod] Login"
    url: https://rentmigo.co.uk/login
  - name: "[Prod] Auth API"
    url: https://rentmigo.co.uk/api/auth
  - name: "[Prod] Landlord API"
    url: https://rentmigo.co.uk/api/v1/landlord
  - name: "[Prod] Health Check"
    url: https://rentmigo.co.uk/api/health

  # Staging
  - name: "[Staging] Website"
    url: https://staging.rentmigo.co.uk
  - name: "[Staging] Login"
    url: https://staging.rentmigo.co.uk/login
  - name: "[Staging] Auth API"
    url: https://staging.rentmigo.co.uk/api/auth
  - name: "[Staging] Landlord API"
    url: https://staging.rentmigo.co.uk/api/v1/landlord
  - name: "[Staging] Health Check"
    url: https://staging.rentmigo.co.uk/api/health

status-website:
  baseUrl: /Rentmigo-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rentr UK Status
  introTitle: "**Rentr UK** uptime monitor and status page."
  introMessage: Real-time uptime data for Rentr UK services. Target uptime 99.5%.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
