owner: Rentr-UK
repo: Rentmigo-uptime

sites:
  # Production
  - name: "[Prod] Website"
    url: https://rentmigo.co.uk
    expectedStatusCodes:
      - 200
      - 301
      - 429
  - name: "[Prod] Login"
    url: https://rentmigo.co.uk/login
    expectedStatusCodes:
      - 200
      - 301
      - 429
  - name: "[Prod] Auth API"
    url: https://rentmigo.co.uk/api/auth/session
    expectedStatusCodes:
      - 200
      - 301
      - 401
      - 429
  - name: "[Prod] Health Check"
    url: https://rentmigo.co.uk/api/v1/health
    expectedStatusCodes:
      - 200
      - 301
      - 429

status-website:
  baseUrl: /Rentmigo-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rentr UK Status
  theme: light
  introTitle: "**Rentr UK** uptime monitor and status page."
  introMessage: Real-time uptime data for Rentr UK services. Target uptime 99.5%.
