owner: Rentr-UK
repo: Rentmigo-uptime

sites:
  # Production (uses Vercel protection bypass to avoid rate limiting)
  - name: "[Prod] Website"
    url: https://rentmigo.co.uk
    headers:
      - "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET"
    expectedStatusCodes:
      - 200
      - 301
  - name: "[Prod] Login"
    url: https://rentmigo.co.uk/login
    headers:
      - "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET"
    expectedStatusCodes:
      - 200
      - 301
  - name: "[Prod] API Health Check"
    url: https://rentmigo.co.uk/api/v1/health
    headers:
      - "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET"
    expectedStatusCodes:
      - 200
      - 301

  # Staging (uses Vercel protection bypass header)
  - name: "[Staging] Website"
    url: https://staging.rentmigo.co.uk
    headers:
      - "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET"
    expectedStatusCodes:
      - 200
      - 301
  - name: "[Staging] Login"
    url: https://staging.rentmigo.co.uk/login
    headers:
      - "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET"
    expectedStatusCodes:
      - 200
      - 301
  - name: "[Staging] API Health Check"
    url: https://staging.rentmigo.co.uk/api/v1/health
    headers:
      - "x-vercel-protection-bypass: $VERCEL_AUTOMATION_BYPASS_SECRET"
    expectedStatusCodes:
      - 200
      - 301

  # Core Services (third-party dependencies)
  - name: Vercel
    url: https://www.vercel-status.com/api/v2/status.json
    expectedStatusCodes:
      - 200
  - name: Neon
    url: https://neonstatus.com
    expectedStatusCodes:
      - 200
  - name: Stripe
    url: https://status.stripe.com/current
    expectedStatusCodes:
      - 200
  - name: Inngest
    url: https://status.inngest.com/api/v2/status.json
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /Rentmigo-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rentr UK Status
  theme: light
  introTitle: "**Rentr UK** uptime monitor and status page."
  introMessage: Real-time uptime data for Rentr UK services. Target uptime 99.5%.
